# Podfile
use_frameworks!

target 'Supr-demo' do
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
end

# RxTests and RxBlocking make the most sense in the context of unit/integration tests
target 'Supr-demoTests' do
  pod 'RxBlocking', '~> 4.0'
  pod 'RxTest',     '~> 4.0'
end
